#region

using System;
using System.Collections.Generic;
using YamlDotNet.Serialization;

#endregion

namespace ChaoticOnyx.Tools.ChangelogGenerator
{
    /// <summary>
    ///     Конвертеры кэша.
    /// </summary>
    public static class CacheFormatConverter
    {
        /// <summary>
        ///     Конвертирует старый /VG/ формат кэша в нормальный.
        /// </summary>
        public static List<Changelog> VgToChaoticOnyx(IDeserializer deserializer, string text)
        {
            text = text.Replace(@"DO NOT EDIT THIS FILE BY HAND!  AUTOMATICALLY GENERATED BY ss13_genchangelog.py.
---", "");
            
            var cache =
                deserializer.Deserialize<Dictionary<DateTime, Dictionary<string, List<Dictionary<string, string>>>>>(text);

            var changelogs = new List<Changelog>();

            foreach (var (date, authors) in cache)
            {
                foreach (var (author, changes) in authors)
                {
                    List<Change> changesList = new();

                    foreach (var change in changes)
                    {
                        foreach (var (prefix, message) in change)
                        {
                            changesList.Add(new()
                            {
                                Prefix = prefix, Message = message
                            });
                        }
                    }
                    
                    var changelog = new Changelog
                    {
                        Author = author, Date = date, Changes = changesList, DeleteAfter = false
                    };

                    changelogs.Add(changelog);
                }
            }

            return changelogs;
        }
    }
}
