//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChaoticOnyx.Tools.ChangelogGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChangelogGeneratorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChangelogGeneratorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChaoticOnyx.Tools.ChangelogGenerator.resources.ChangelogGeneratorResources", typeof(ChangelogGeneratorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache converted!.
        /// </summary>
        internal static string CACHE_CONVERTED {
            get {
                return ResourceManager.GetString("CACHE_CONVERTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache has non convertable format.
        /// </summary>
        internal static string CANT_CONVERT_CACHE {
            get {
                return ResourceManager.GetString("CANT_CONVERT_CACHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog saved.
        /// </summary>
        internal static string CHANGELOG_SAVED {
            get {
                return ResourceManager.GetString("CHANGELOG_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application configured.
        /// </summary>
        internal static string DBG_CONFIGURED {
            get {
                return ResourceManager.GetString("DBG_CONFIGURED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded options:.
        /// </summary>
        internal static string DBG_LOADED_OPTIONS {
            get {
                return ResourceManager.GetString("DBG_LOADED_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting file.
        /// </summary>
        internal static string DELETING_FILE {
            get {
                return ResourceManager.GetString("DELETING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        /// </summary>
        internal static string FILE_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("FILE_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder does not exist.
        /// </summary>
        internal static string FOLDER_DOES_NOT_EXISTS {
            get {
                return ResourceManager.GetString("FOLDER_DOES_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new changelogs.
        /// </summary>
        internal static string NO_NEW_CHANGELOGS {
            get {
                return ResourceManager.GetString("NO_NEW_CHANGELOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing cache file.
        /// </summary>
        internal static string PARSING_CACHE_FILE {
            get {
                return ResourceManager.GetString("PARSING_CACHE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing error in.
        /// </summary>
        internal static string PARSING_ERROR {
            get {
                return ResourceManager.GetString("PARSING_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing file.
        /// </summary>
        internal static string PARSING_FILE {
            get {
                return ResourceManager.GetString("PARSING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving cache.
        /// </summary>
        internal static string SAVING_CACHE {
            get {
                return ResourceManager.GetString("SAVING_CACHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving changelogs.
        /// </summary>
        internal static string SAVING_CHANGELOGS {
            get {
                return ResourceManager.GetString("SAVING_CHANGELOGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching changelogs in.
        /// </summary>
        internal static string SEARCHING_CHANGELOGS_IN {
            get {
                return ResourceManager.GetString("SEARCHING_CHANGELOGS_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache has invalid format, trying to convert it.
        /// </summary>
        internal static string TRYING_TO_CONVERT {
            get {
                return ResourceManager.GetString("TRYING_TO_CONVERT", resourceCulture);
            }
        }
    }
}
